spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mojabaza
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring.jpa.hibernate.ddl-auto: update
